# Generated by Django 2.1 on 2018-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('go_pay_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
