# Generated by Django 2.1 on 2018-08-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_balance', models.IntegerField()),
                ('description', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('user_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Balance', to_field='user')),
            ],
        ),
    ]
